-- SQL RPG bootstrap for Supabase Postgres
-- Run in Supabase SQL Editor.

create table if not exists public.challenges (
  id bigint generated by default as identity primary key,
  prompt text not null,
  difficulty text not null check (difficulty in ('easy', 'medium', 'hard')),
  hint text,
  expected_signature text not null
);

create table if not exists public.goblins (
  id bigint generated by default as identity primary key,
  name text not null,
  hp integer not null check (hp > 0),
  dungeon text not null
);

create table if not exists public.player_progress (
  user_id uuid primary key references auth.users(id) on delete cascade,
  level integer not null default 1,
  xp integer not null default 0,
  gold integer not null default 0,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  challenge_id bigint not null references public.challenges(id) on delete cascade,
  sql_text text not null,
  success boolean not null,
  feedback text not null,
  damage integer not null default 0,
  critical boolean not null default false,
  xp_awarded integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create or replace function public.execute_arena_sql(query_text text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  payload jsonb;
begin
  if query_text is null or btrim(query_text) = '' then
    raise exception 'Query bos olamaz';
  end if;

  if query_text ~ ';' then
    raise exception 'Noktali virgul yasak';
  end if;

  if query_text !~* '^\s*select\b' then
    raise exception 'Sadece SELECT sorgusu kabul edilir';
  end if;

  if query_text ~* '\m(insert|update|delete|drop|alter|create|grant|revoke|truncate)\M' then
    raise exception 'Yazma veya DDL komutlari yasak';
  end if;

  perform set_config('statement_timeout', '3000', true);

  execute format('select coalesce(jsonb_agg(row_to_json(t)), ''[]''::jsonb) from (%s) t', query_text)
  into payload;

  return coalesce(payload, '[]'::jsonb);
end;
$$;

revoke all on function public.execute_arena_sql(text) from public;
grant execute on function public.execute_arena_sql(text) to anon, authenticated;

alter table public.player_progress enable row level security;
alter table public.attempts enable row level security;

drop policy if exists "progress_select_own" on public.player_progress;
create policy "progress_select_own"
on public.player_progress for select
using (auth.uid() = user_id);

drop policy if exists "progress_insert_own" on public.player_progress;
create policy "progress_insert_own"
on public.player_progress for insert
with check (auth.uid() = user_id);

drop policy if exists "progress_update_own" on public.player_progress;
create policy "progress_update_own"
on public.player_progress for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "attempts_select_own" on public.attempts;
create policy "attempts_select_own"
on public.attempts for select
using (auth.uid() = user_id);

drop policy if exists "attempts_insert_own" on public.attempts;
create policy "attempts_insert_own"
on public.attempts for insert
with check (auth.uid() = user_id);

insert into public.goblins (name, hp, dungeon)
select * from (
  values
    ('Goblin Scout', 18, 'Sewer'),
    ('Goblin Bruiser', 32, 'Sewer'),
    ('Goblin Shaman', 22, 'Ruins'),
    ('Goblin Captain', 45, 'Ruins')
) as seed(name, hp, dungeon)
where not exists (select 1 from public.goblins);

insert into public.challenges (prompt, difficulty, hint, expected_signature)
select * from (
  values
    (
      'Goblins tablosundaki en dusuk HP degerine sahip dusmani bul.',
      'easy',
      'ORDER BY hp ASC LIMIT 1 kullanabilirsin.',
      'min-goblin-hp'
    ),
    (
      'Her zindandaki goblin sayisini listele.',
      'medium',
      'GROUP BY dungeon kullan.',
      'goblin-count-by-dungeon'
    ),
    (
      'HP degeri 20den buyuk goblinleri HP azalan sirada getir.',
      'hard',
      'WHERE + ORDER BY birlesimi kullan.',
      'high-hp-goblins'
    )
) as seed(prompt, difficulty, hint, expected_signature)
where not exists (select 1 from public.challenges);

-- Edge Function contract expected by app:
-- name: submit-sql
-- body: { challengeId: number, sql: string }
-- response: { success: boolean, feedback: string, damage: number, critical: boolean, xpAwarded: number }
